# Generated by Django 3.2.4 on 2021-06-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='species',
        ),
        migrations.AddField(
            model_name='people',
            name='species',
            field=models.ManyToManyField(to='swapi.Species'),
        ),
        migrations.RemoveField(
            model_name='people',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='people',
            name='vehicles',
            field=models.ManyToManyField(to='swapi.Vehicles'),
        ),
    ]
